### ISSUE TITLE
Slugify not removing slashes in episode names

### ISSUE THREAD

**Issue by monkecoder42** [janw/podcast-archiver#148]
When downloading a podcast episode with a name that contains a slash character, with the "slugify" option enabled, some unexpected behavior occured: For example, if the show name is "AAA", date "YYYY-MM-DD" and episode name "BBB / CCC", the file was saved in the path `out/AAAA/YYYY-MM-DD BBB-/-CCC.mp3`. So the slash character was not removed by slugify which led to the creation of a subdirectory. Instead I would have expected the path to be  `out/AAAA/YYYY-MM-DD BBB---CCC.mp3`, with the slash replaced by a dash.

**Comment by janw** [comment]
Fixed in v1.4.1. Thank you!
