### ISSUE TITLE
Episode marked as downloaded even when download failed

### ISSUE THREAD

**Issue by alxk0909** [janw/podcast-archiver#209]
When an episode fails to download:
```
ERROR Download failed: #255: Joker - Folie À Deux & New York, New York (2024-10-14); HTTPSConnectionPool(host='podcast.orf.at', port=443): Read timed out.
....
✔ Archived all episodes for: FM4 Film Podcast
Done.
```
and the application is run again, the episode is marked as downloaded and no re-download is tried, even though the file does not exist:

```
✔ Exists: #255: Joker - Folie À Deux & New York, New York (2024-10-14)
```
only once the database is deleted, the file is re-downloaded.
Occurred with settings: `--write-info-json -f https://podcast.orf.at/podcast/fm4/fm4_film/fm4_film.xml`

**Comment by janw** [comment]
Thanks for reporting! 🙌
