### ISSUE TITLE
Add support for custom file names based on mp3 tags and/or feed metadata

### ISSUE THREAD

**Issue by Xaelias** [janw/podcast-archiver#21]
Hey!
First thanks for this, it looks like it's working great.
But the things I download end up with names like `HSW2182542043.mp3` which... isn't super useful :-D
It would be awesome if podcast-archiver could automatically rename that based on the tags of the mp3 files.
I understand that there are probably programs out there that already do that, but I figured I would still offer the idea here.
Especially since renaming with a 3rd party program makes not downloading older episode tricky.
Thanks!

**Comment by Xaelias** [comment]
I realize this is probably not practical.

**Comment by janw** [comment]
Hi @Xaelias! Thanks for the idea! I do agree with it in general. A proper way to use custom episode naming is definitely a feature I'd like to implement in the future. Not sure, if I'd be going with mp3 tags but rather use the metadata contained in a podcast's feed but nonetheless I'll reopen this ticket, and keep it around until I'll get around to doing something about it. 

Thanks again! 👋

**Comment by Xaelias** [comment]
Yeah I've done something hack-ish using the metadata in the feed itself for the few podcasts I started archiving.
But even with only a few, the number of tweaks I had to come up with to get something that mostly looks good is... not a good omen for something that would fit most streams out of the box.

**Comment by ddmunhoz** [comment]
I added my implementation to this issue. Since no much discussion was held on the feature/process I decided to not disturb he original intent/code and added it as an optional argument -n. So when adding -n to the cmd line it will create file names following the pattern:

```
Podcast_Name - [Episode_Name]
```

**Comment by janw** [comment]
Added in #50, shipped as part of v1.0.0, see https://github.com/janw/podcast-archiver#changing-the-filename-format
