### ISSUE TITLE
Unable to download multiple episodes from Simplecast

### ISSUE THREAD

**Issue by todd-dunagan** [janw/podcast-archiver#23]
Hey there, really appreciate this tool, thank you for its existence!

I've been attempting to download podcasts from simplecast and notice that only one episode is able to pulled down. Filename = default_tc.mp3 with no real metadata attached. Have you seen this before? Wondering if I'm not using the script arguments correctly.? Example feed: https://feeds.simplecast.com/_X4DUqDS

**Comment by todd-dunagan** [comment]
Closing as duplicate / solved by: https://github.com/janw/podcast-archiver/issues/12

**Comment by janw** [comment]
Hey Todd, thanks for pointing this out again. I've been on a hiatus with the project for a while, but I will probably pick it up again soon and certainly take care of this issue.
